//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormSDB.WcfServiceSDB {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterSDB", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSDB")]
    [System.SerializableAttribute()]
    public partial class FilterSDB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientBook {
            get {
                return this.ClientBookField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBookField, value) != true)) {
                    this.ClientBookField = value;
                    this.RaisePropertyChanged("ClientBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartPeriod {
            get {
                return this.StartPeriodField;
            }
            set {
                if ((this.StartPeriodField.Equals(value) != true)) {
                    this.StartPeriodField = value;
                    this.RaisePropertyChanged("StartPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MySqlException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSDB")]
    [System.SerializableAttribute()]
    public partial class MySqlException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceSDB.IServiceSDB")]
    public interface IServiceSDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientInfo", ReplyAction="http://tempuri.org/IServiceSDB/GetClientInfoResponse")]
        System.Data.DataSet GetClientInfo(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientInfo", ReplyAction="http://tempuri.org/IServiceSDB/GetClientInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetClientInfoAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetBook", ReplyAction="http://tempuri.org/IServiceSDB/GetBookResponse")]
        System.Data.DataSet GetBook(WinFormSDB.WcfServiceSDB.FilterSDB filter, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetBook", ReplyAction="http://tempuri.org/IServiceSDB/GetBookResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookAsync(WinFormSDB.WcfServiceSDB.FilterSDB filter, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientStatistics", ReplyAction="http://tempuri.org/IServiceSDB/GetClientStatisticsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WinFormSDB.WcfServiceSDB.MySqlException), Action="http://tempuri.org/IServiceSDB/GetClientStatisticsMySqlExceptionFault", Name="MySqlException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSDB")]
        System.Data.DataSet GetClientStatistics(WinFormSDB.WcfServiceSDB.FilterSDB filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientStatistics", ReplyAction="http://tempuri.org/IServiceSDB/GetClientStatisticsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetClientStatisticsAsync(WinFormSDB.WcfServiceSDB.FilterSDB filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSDBChannel : WinFormSDB.WcfServiceSDB.IServiceSDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSDBClient : System.ServiceModel.ClientBase<WinFormSDB.WcfServiceSDB.IServiceSDB>, WinFormSDB.WcfServiceSDB.IServiceSDB {
        
        public ServiceSDBClient() {
        }
        
        public ServiceSDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetClientInfo(string address) {
            return base.Channel.GetClientInfo(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetClientInfoAsync(string address) {
            return base.Channel.GetClientInfoAsync(address);
        }
        
        public System.Data.DataSet GetBook(WinFormSDB.WcfServiceSDB.FilterSDB filter, string address) {
            return base.Channel.GetBook(filter, address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookAsync(WinFormSDB.WcfServiceSDB.FilterSDB filter, string address) {
            return base.Channel.GetBookAsync(filter, address);
        }
        
        public System.Data.DataSet GetClientStatistics(WinFormSDB.WcfServiceSDB.FilterSDB filter) {
            return base.Channel.GetClientStatistics(filter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetClientStatisticsAsync(WinFormSDB.WcfServiceSDB.FilterSDB filter) {
            return base.Channel.GetClientStatisticsAsync(filter);
        }
    }
}
